---
title: "Hello!"
author: "Jason Risdana"
date: '2020-05-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```
Welcome to my website! Glad you're here. 
<!--more-->
Thank you for visiting my website! I plan on posting short projects, exercises and things related to statistics and data science on my home page (which you can access by clicking my name in the top-left corner). For more information about me, my interests and why I do what I do, check out my [<kbd>About</kbd>](/about/) and [<kbd>Resume</kbd>](/resume) page.
<br><br> 
If you need to look for anything, try my [<kbd>Search</kbd>](/search) page. You can view all of my posts in my [<kbd>Archives</kbd>](/archives) page. 
My website was made using [<kbd>blogdown</kbd>](https://bookdown.org/yihui/blogdown/).
<br><br> 
I tend to abuse the kbd tag. Anything that looks like <kbd>this</kbd> will link to another page on my website or a site that has more information on a package I used in a post/project. I thought it would add some personality to the hyperlinks. All other hyperlinks (sources, etc) will look light purple - nothing crazy. 